// =============================================================================
// MamlMetaLossExplorer.tsx
//
// §2.5 MAML on sinusoidal regression. Reader-controlled (α, N) sliders pick
// among 9 precomputed training runs (α ∈ {0.005, 0.01, 0.02}, N ∈ {3, 5, 8}).
// The viz shows the selected meta-loss curve on log axes plus the held-out
// task's adaptation evolution at four inner-step counts at the default config.
//
// Data: fetched from /sample-data/meta-learning/maml_loss.json (dual-located
// per CLAUDE.md). Generated by notebooks/meta-learning/precompute_maml_loss.py.
//
// Static fallback: /images/topics/meta-learning/05_maml_meta_loss.png and
//                  /images/topics/meta-learning/06_maml_adaptation_evolution.png
// =============================================================================

import { useEffect, useMemo, useState } from 'react';
import * as d3 from 'd3';
import { useResizeObserver } from './shared/useResizeObserver';
import { useD3 } from './shared/useD3';
import { META_PALETTE } from './shared/meta-learning';

interface MamlLossCurve {
  alpha: number;
  N: number;
  metaLoss: number[];
  lossAtEnd: number;
}

interface MamlLossPayload {
  alphaGrid: number[];
  NGrid: number[];
  curves: MamlLossCurve[];
  defaultIndex: number;
  adaptationXSupport: number[];
  adaptationYSupport: number[];
  adaptationXDense: number[];
  adaptationYTrue: number[];
  adaptationPredsByStep: Record<string, number[]>;
}

const SM_BREAKPOINT = 640;

export default function MamlMetaLossExplorer(): React.JSX.Element {
  const [payload, setPayload] = useState<MamlLossPayload | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [alphaIdx, setAlphaIdx] = useState<number | null>(null);
  const [NIdx, setNIdx] = useState<number | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetch('/sample-data/meta-learning/maml_loss.json')
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json();
      })
      .then((data: MamlLossPayload) => {
        if (cancelled) return;
        setPayload(data);
        const def = data.curves[data.defaultIndex];
        setAlphaIdx(data.alphaGrid.indexOf(def.alpha));
        setNIdx(data.NGrid.indexOf(def.N));
      })
      .catch((e) => {
        if (!cancelled) setError(String(e));
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const { ref: containerRef, width: containerWidth } = useResizeObserver<HTMLDivElement>();
  const isMobile = (containerWidth || 800) < SM_BREAKPOINT;
  const panelWidth = isMobile ? containerWidth || 320 : (containerWidth || 800) / 2 - 12;
  const panelHeight = 260;

  const selectedCurve = useMemo(() => {
    if (!payload || alphaIdx === null || NIdx === null) return null;
    const a = payload.alphaGrid[alphaIdx];
    const N = payload.NGrid[NIdx];
    return payload.curves.find((c) => Math.abs(c.alpha - a) < 1e-9 && c.N === N) || null;
  }, [payload, alphaIdx, NIdx]);

  const leftRef = useD3<SVGSVGElement>(
    (svg) => {
      svg.selectAll('*').remove();
      if (!selectedCurve || panelWidth <= 0) return;
      const margin = { top: 18, right: 12, bottom: 36, left: 50 };
      const innerW = panelWidth - margin.left - margin.right;
      const innerH = panelHeight - margin.top - margin.bottom;
      if (innerW <= 0 || innerH <= 0) return;
      const g = svg.append('g').attr('transform', `translate(${margin.left},${margin.top})`);
      const xs = selectedCurve.metaLoss.map((_, i) => i);
      const xScale = d3.scaleLinear().domain([0, xs.length - 1]).range([0, innerW]);
      const yMax = Math.max(...selectedCurve.metaLoss) * 1.05;
      const yMin = Math.max(0.05, Math.min(...selectedCurve.metaLoss) * 0.9);
      const yScale = d3.scaleLog().domain([yMin, yMax]).range([innerH, 0]);
      g.append('g')
        .attr('transform', `translate(0, ${innerH})`)
        .call(d3.axisBottom(xScale).ticks(5).tickFormat(d3.format('d')))
        .selectAll('text')
        .style('fill', 'var(--color-text)');
      g.append('g').call(d3.axisLeft(yScale).ticks(5, '.1f')).selectAll('text').style('fill', 'var(--color-text)');
      g.append('text').attr('x', innerW / 2).attr('y', innerH + 30).attr('text-anchor', 'middle').style('fill', 'var(--color-text-secondary)').style('font-size', '11px').text('meta-iteration');
      g.append('text').attr('transform', 'rotate(-90)').attr('x', -innerH / 2).attr('y', -36).attr('text-anchor', 'middle').style('fill', 'var(--color-text-secondary)').style('font-size', '11px').text('meta-loss (log)');
      const line = d3.line<number>().x((_, i) => xScale(i)).y((d) => yScale(d));
      g.append('path').datum(selectedCurve.metaLoss).attr('d', line).style('fill', 'none').style('stroke', META_PALETTE[0]).style('stroke-width', 1.5);
    },
    [selectedCurve, panelWidth],
  );

  const rightRef = useD3<SVGSVGElement>(
    (svg) => {
      svg.selectAll('*').remove();
      if (!payload || panelWidth <= 0) return;
      const margin = { top: 18, right: 12, bottom: 36, left: 50 };
      const innerW = panelWidth - margin.left - margin.right;
      const innerH = panelHeight - margin.top - margin.bottom;
      if (innerW <= 0 || innerH <= 0) return;
      const g = svg.append('g').attr('transform', `translate(${margin.left},${margin.top})`);
      const xScale = d3.scaleLinear().domain([-5, 5]).range([0, innerW]);
      const yScale = d3.scaleLinear().domain([-6, 6]).range([innerH, 0]);
      g.append('g').attr('transform', `translate(0, ${innerH})`).call(d3.axisBottom(xScale).ticks(5)).selectAll('text').style('fill', 'var(--color-text)');
      g.append('g').call(d3.axisLeft(yScale).ticks(5)).selectAll('text').style('fill', 'var(--color-text)');
      g.append('text').attr('x', innerW / 2).attr('y', innerH + 30).attr('text-anchor', 'middle').style('fill', 'var(--color-text-secondary)').style('font-size', '11px').text('x (held-out task: A=3.2, φ=1.7)');
      // truth
      const tLine = d3.line<number>().x((_, i) => xScale(payload.adaptationXDense[i])).y((d) => yScale(d));
      g.append('path').datum(payload.adaptationYTrue).attr('d', tLine).style('fill', 'none').style('stroke', 'var(--color-text)').style('stroke-width', 1.2).style('opacity', 0.7);
      // predictions at each step
      const steps = [0, 1, 3, 5];
      steps.forEach((n, idx) => {
        const preds = payload.adaptationPredsByStep[String(n)];
        if (!preds) return;
        const pLine = d3.line<number>().x((_, i) => xScale(payload.adaptationXDense[i])).y((d) => yScale(d));
        g.append('path').datum(preds).attr('d', pLine).style('fill', 'none').style('stroke', META_PALETTE[idx]).style('stroke-width', 1.4);
      });
      // support points
      payload.adaptationXSupport.forEach((x, i) => {
        g.append('circle').attr('cx', xScale(x)).attr('cy', yScale(payload.adaptationYSupport[i])).attr('r', 4).style('fill', META_PALETTE[3]).style('stroke', 'white').style('stroke-width', 0.8);
      });
      // legend
      const legendG = g.append('g').attr('transform', `translate(${innerW - 100}, 8)`);
      legendG.append('rect').attr('width', 12).attr('height', 3).attr('y', 5).style('fill', 'var(--color-text)').style('opacity', 0.7);
      legendG.append('text').attr('x', 16).attr('y', 8).style('fill', 'var(--color-text)').style('font-size', '10px').text('true sinusoid');
      steps.forEach((n, idx) => {
        legendG.append('rect').attr('width', 12).attr('height', 3).attr('y', 5 + (idx + 1) * 13).style('fill', META_PALETTE[idx]);
        legendG.append('text').attr('x', 16).attr('y', 8 + (idx + 1) * 13).style('fill', 'var(--color-text)').style('font-size', '10px').text(`n=${n} steps`);
      });
    },
    [payload, panelWidth],
  );

  return (
    <div ref={containerRef} style={{ width: '100%' }}>
      <div style={{ display: 'flex', gap: 12, marginBottom: 8, alignItems: 'center', fontSize: 11 }}>
        {payload && alphaIdx !== null && NIdx !== null ? (
          <>
            <label style={{ flex: 1 }}>
              α (inner step): <strong>{payload.alphaGrid[alphaIdx]}</strong>
              <input type="range" min={0} max={payload.alphaGrid.length - 1} step={1} value={alphaIdx} onChange={(e) => setAlphaIdx(Number(e.target.value))} style={{ width: '100%' }} aria-label="alpha" />
            </label>
            <label style={{ flex: 1 }}>
              N (inner steps): <strong>{payload.NGrid[NIdx]}</strong>
              <input type="range" min={0} max={payload.NGrid.length - 1} step={1} value={NIdx} onChange={(e) => setNIdx(Number(e.target.value))} style={{ width: '100%' }} aria-label="N" />
            </label>
          </>
        ) : (
          <span style={{ color: 'var(--color-text-secondary)' }}>{error ? `Error loading data: ${error}` : 'Loading precomputed meta-loss curves…'}</span>
        )}
      </div>
      <div style={{ display: 'flex', flexDirection: isMobile ? 'column' : 'row', gap: 16 }}>
        <svg ref={leftRef} width={panelWidth} height={panelHeight} role="img" aria-label="meta-loss curve" />
        <svg ref={rightRef} width={panelWidth} height={panelHeight} role="img" aria-label="adaptation evolution at default config" />
      </div>
      <p style={{ fontSize: 10.5, color: 'var(--color-text-secondary)' }}>
        Left: meta-training loss curve at the selected (α, N). Right: held-out task adaptation at the default (α=0.01, N=5). Across the 3×3 grid, the curve shape stays bounded and doesn't show strong monotonic descent — the topic's "convergence" claim is qualitative across this hyperparameter range.
      </p>
    </div>
  );
}
