// =============================================================================
// verify-variational-bayes-for-model-selection.ts
//
// Numerical regression tests for the VBMS primitives in
// src/components/viz/shared/bayesian-ml.ts against the printed outputs of
//   notebooks/variational-bayes-for-model-selection/
//     01_variational_bayes_for_model_selection.ipynb
//
// Run with: pnpm verify:variational-bayes-for-model-selection
// Accumulates failures and exits non-zero at the end if any checks fail.
//
// The polynomial-regression spine of §1 / §3 / §5 / §8 / §9 / §10 uses a fixed
// y array generated by NumPy's PCG64 with seed 20260508 — captured below as a
// test fixture so the TS port can match notebook outputs exactly without
// reimplementing PCG64.
//
// Tolerances:
//   - Closed-form quantities (marginal likelihood, Laplace, mean-field ELBO):
//     1e-3 absolute (allows for small float64 vs Cholesky-solve drift).
//   - Laplace = closed-form (Gaussian conjugate): 1e-9 absolute.
//   - Bits-back identity (Monte Carlo, S = 5e4): 0.05 absolute.
//   - IWELBO at K=1 vs ELBO (Monte Carlo, S=2000): 0.10 absolute.
//   - IWELBO at K=1000 (Monte Carlo, S=200): 0.30 absolute.
//   - AIS at T=100 (200 chains, exact-Gaussian sampling): 0.30 absolute.
// =============================================================================

import {
  bitsBackCodingExpectedLength,
  iwelboEstimate,
  laplaceApproximation,
  makeMeanFieldGaussianSampler,
  marginalLikelihoodGaussianRegression,
  meanFieldELBOGaussianRegression,
  meanFieldGaussianLogDensity,
  mulberry32,
  gaussianPair,
  polynomialDesignMatrix,
  polynomialJointLogProb,
  polynomialPosteriorMoments,
  aisEstimate,
  bicApproximation,
} from '../bayesian-ml';

// -----------------------------------------------------------------------------
// Fixed test fixtures — captured from the notebook §1 cell run with SEED=20260508
// -----------------------------------------------------------------------------

const N = 30;
const SIGMA2 = 0.0625; // = 0.25²
const TAU2 = 4.0;

function linspace(a: number, b: number, n: number): number[] {
  const out = new Array<number>(n);
  for (let i = 0; i < n; i++) out[i] = a + ((b - a) * i) / (n - 1);
  return out;
}

const X_GRID = linspace(-1.0, 1.0, N);

// y array printed from the notebook (NumPy PCG64 seed=20260508).
// Captured 2026-05-08 from .venv/bin/python via the §1 cell.
const Y_FIXED: number[] = [
  -0.6800341583638437, -0.6713683737999192, 0.42393608741006306, -0.18415011140592086,
  0.4392941340513951, 0.401582941643184, 0.5767018005195377, 0.7366067978058071,
  0.9685107342232395, 1.2530275339208585, 0.5639749530625211, 0.8229686955412666,
  0.8714689006673965, 0.8850933446551065, 0.37495678320087766, 0.3984638659202808,
  0.01671499435523549, 0.14515680583738416, -0.0663580519877901, 0.8061700843018722,
  0.5567837571476506, 0.35427849216268303, -0.043878391287867025, 0.2962324867317664,
  0.2688206220970354, 0.3847392672095318, 0.7510136535577099, 1.1020278717873264,
  1.550050451751259, 2.0483306722458696,
];

// Notebook printed values (from §1 cell stdout): { d, log_p, laplace, MF_ELBO }
const NOTEBOOK_TABLE = [
  { d: 1, logP: -54.8448, laplace: -54.8448, mfElbo: -54.8448 },
  { d: 2, logP: -57.4555, laplace: -57.4555, mfElbo: -57.8601 },
  { d: 3, logP: -14.0279, laplace: -14.0279, mfElbo: -15.3411 },
  { d: 4, logP: -15.0120, laplace: -15.0120, mfElbo: -17.7519 },
  { d: 5, logP: -15.5943, laplace: -15.5943, mfElbo: -20.1689 },
  { d: 6, logP: -15.9731, laplace: -15.9731, mfElbo: -22.5347 },
  { d: 7, logP: -16.6187, laplace: -16.6187, mfElbo: -25.1808 },
  { d: 8, logP: -17.0954, laplace: -17.0954, mfElbo: -27.7182 },
  { d: 9, logP: -17.5720, laplace: -17.5720, mfElbo: -30.2869 },
];

// -----------------------------------------------------------------------------
// Tiny test harness (matches verify-bayesian-neural-networks.ts conventions)
// -----------------------------------------------------------------------------

let passed = 0;
let failed = 0;
const rows: Array<{ test: string; expected: string; observed: string; ok: boolean }> = [];

function record(test: string, expected: number, observed: number, tol: number): boolean {
  const diff = Math.abs(expected - observed);
  const ok = diff <= tol;
  rows.push({
    test,
    expected: expected.toFixed(4),
    observed: observed.toFixed(4),
    ok,
  });
  if (ok) passed += 1;
  else failed += 1;
  return ok;
}

function header(s: string): void {
  console.log(`\n=== ${s} ===`);
}

// -----------------------------------------------------------------------------
// 1. Closed-form polynomial-regression spine (§1, §5)
// -----------------------------------------------------------------------------

header('1. Closed-form Gaussian-conjugate evidence (§1)');

for (const ref of NOTEBOOK_TABLE) {
  const X = polynomialDesignMatrix(X_GRID, ref.d);
  const observed = marginalLikelihoodGaussianRegression(X, Y_FIXED, SIGMA2, TAU2);
  record(`marginalLikelihood d=${ref.d}`, ref.logP, observed, 1e-3);
}

// -----------------------------------------------------------------------------
// 2. Laplace approximation = closed-form for Gaussian conjugate (§3 Theorem 2)
// -----------------------------------------------------------------------------

header('2. Laplace approximation matches closed-form (Gaussian conjugate, §3)');

for (const ref of [NOTEBOOK_TABLE[2], NOTEBOOK_TABLE[3], NOTEBOOK_TABLE[8]]) {
  // d ∈ {3, 4, 9}: Laplace must equal closed-form to numerical precision for
  // Gaussian-conjugate models (notebook §1 asserts allclose at atol=1e-10).
  // We compare against the full-precision closed-form rather than the
  // 4-decimal printed reference.
  const X = polynomialDesignMatrix(X_GRID, ref.d);
  const { mean, precision } = polynomialPosteriorMoments(X, Y_FIXED, SIGMA2, TAU2);
  const closedForm = marginalLikelihoodGaussianRegression(X, Y_FIXED, SIGMA2, TAU2);
  const jointLogProb = (theta: number[]): number =>
    polynomialJointLogProb(theta, X, Y_FIXED, SIGMA2, TAU2);
  const observed = laplaceApproximation(jointLogProb, mean, precision);
  record(`laplace = closed-form d=${ref.d}`, closedForm, observed, 1e-10);
}

// -----------------------------------------------------------------------------
// 3. Mean-field ELBO closed-form (§6.3 formula on Gaussian targets)
// -----------------------------------------------------------------------------

header('3. Mean-field ELBO closed-form (§6.3)');

for (const ref of NOTEBOOK_TABLE) {
  const X = polynomialDesignMatrix(X_GRID, ref.d);
  const observed = meanFieldELBOGaussianRegression(X, Y_FIXED, SIGMA2, TAU2);
  record(`meanFieldELBO d=${ref.d}`, ref.mfElbo, observed, 1e-3);
}

// -----------------------------------------------------------------------------
// 4. Bits-back identity (Monte Carlo, §10 Theorem 8 verification)
// -----------------------------------------------------------------------------

header('4. Bits-back identity bits-back-net = -ELBO (Monte Carlo, §10)');

{
  const d = 4;
  const X = polynomialDesignMatrix(X_GRID, d);
  const { mean, precision } = polynomialPosteriorMoments(X, Y_FIXED, SIGMA2, TAU2);
  const std = precision.map((_, i) => Math.sqrt(1 / precision[i][i]));
  const elbo = meanFieldELBOGaussianRegression(X, Y_FIXED, SIGMA2, TAU2);
  const logEvidence = marginalLikelihoodGaussianRegression(X, Y_FIXED, SIGMA2, TAU2);
  const qSampler = makeMeanFieldGaussianSampler(mean, std, 20260508);
  const logQ = (theta: number[]): number => meanFieldGaussianLogDensity(theta, mean, std);
  const logPrior = (theta: number[]): number => {
    let bb = 0;
    for (let i = 0; i < theta.length; i++) bb += theta[i] * theta[i];
    return -0.5 * theta.length * Math.log(2 * Math.PI * TAU2) - 0.5 * bb / TAU2;
  };
  const logLikelihood = (theta: number[]): number => {
    let sse = 0;
    for (let i = 0; i < N; i++) {
      let pred = 0;
      for (let j = 0; j < theta.length; j++) pred += X[i][j] * theta[j];
      const r = Y_FIXED[i] - pred;
      sse += r * r;
    }
    return -0.5 * N * Math.log(2 * Math.PI * SIGMA2) - 0.5 * sse / SIGMA2;
  };
  const { codeLength } = bitsBackCodingExpectedLength(
    qSampler,
    logPrior,
    logQ,
    logLikelihood,
    logEvidence,
    50_000,
  );
  record('bits-back net = -ELBO at d=4', -elbo, codeLength, 0.05);
}

// -----------------------------------------------------------------------------
// 5. IWELBO at K=1 ≈ ELBO; K large → log p(y) (§8 Theorem 6)
// -----------------------------------------------------------------------------

header('5. IWELBO monotone tightness (Monte Carlo, §8)');

{
  const d = 4;
  const X = polynomialDesignMatrix(X_GRID, d);
  const { mean, precision } = polynomialPosteriorMoments(X, Y_FIXED, SIGMA2, TAU2);
  const std = precision.map((_, i) => Math.sqrt(1 / precision[i][i]));
  const elbo = meanFieldELBOGaussianRegression(X, Y_FIXED, SIGMA2, TAU2);
  const logEvidence = marginalLikelihoodGaussianRegression(X, Y_FIXED, SIGMA2, TAU2);
  const logJoint = (theta: number[]): number =>
    polynomialJointLogProb(theta, X, Y_FIXED, SIGMA2, TAU2);
  const logQ = (theta: number[]): number => meanFieldGaussianLogDensity(theta, mean, std);

  const qSampler1 = makeMeanFieldGaussianSampler(mean, std, 11111);
  const observed1 = iwelboEstimate(qSampler1, logJoint, logQ, 1, 2000);
  record('IWELBO K=1 ≈ ELBO', elbo, observed1, 0.10);

  const qSampler1000 = makeMeanFieldGaussianSampler(mean, std, 22222);
  const observed1000 = iwelboEstimate(qSampler1000, logJoint, logQ, 1000, 200);
  // IWELBO at K=1000 should be tighter than K=1; checked below the closed-form
  // value with a lenient one-sided tolerance.
  const ok = observed1000 > elbo - 0.10 && observed1000 < logEvidence + 0.10;
  rows.push({
    test: 'IWELBO K=1000 strictly tighter than ELBO',
    expected: `(${elbo.toFixed(2)}, ${logEvidence.toFixed(2)}]`,
    observed: observed1000.toFixed(4),
    ok,
  });
  if (ok) passed += 1;
  else failed += 1;
}

// -----------------------------------------------------------------------------
// 6. AIS at T=100 ≈ closed-form log p(y) (§9 Theorem 7)
// -----------------------------------------------------------------------------

header('6. AIS converges to closed-form (Monte Carlo, §9)');

{
  const d = 4;
  const X = polynomialDesignMatrix(X_GRID, d);
  const logEvidence = marginalLikelihoodGaussianRegression(X, Y_FIXED, SIGMA2, TAU2);

  // Exact-Gaussian sampling at each schedule step β: posterior precision is
  // X^T X / σ² · β + I / τ², with mean β · cov · X^T y / σ².
  const aisRng = mulberry32(33333);
  let buf: number | null = null;
  const draw = (): number => {
    if (buf !== null) {
      const v = buf;
      buf = null;
      return v;
    }
    const [a, b] = gaussianPair(aisRng);
    buf = b;
    return a;
  };
  const dParam = d + 1;

  // Pre-compute X^T X and X^T y for the schedule
  const XtX = new Array<number>(dParam * dParam).fill(0);
  for (let i = 0; i < dParam; i++) {
    for (let j = 0; j < dParam; j++) {
      let acc = 0;
      for (let k = 0; k < N; k++) acc += X[k][i] * X[k][j];
      XtX[i * dParam + j] = acc;
    }
  }
  const Xty = new Array<number>(dParam).fill(0);
  for (let i = 0; i < dParam; i++) {
    let acc = 0;
    for (let k = 0; k < N; k++) acc += X[k][i] * Y_FIXED[k];
    Xty[i] = acc;
  }

  const exactSampleAtBeta = (beta: number): number[] => {
    const prec: number[][] = [];
    for (let i = 0; i < dParam; i++) {
      const row = new Array<number>(dParam).fill(0);
      for (let j = 0; j < dParam; j++) {
        row[j] = (XtX[i * dParam + j] / SIGMA2) * beta;
        if (i === j) row[j] += 1 / TAU2;
      }
      prec.push(row);
    }
    // Solve prec μ = β X^T y / σ² → μ
    const rhs = new Array<number>(dParam).fill(0);
    for (let i = 0; i < dParam; i++) rhs[i] = (Xty[i] / SIGMA2) * beta;
    const Lp: number[][] = [];
    for (let i = 0; i < dParam; i++) {
      const row = new Array<number>(dParam).fill(0);
      let dii = prec[i][i];
      for (let j = 0; j < i; j++) {
        let acc = prec[i][j];
        for (let k = 0; k < j; k++) acc -= row[k] * Lp[j][k];
        row[j] = acc / Lp[j][j];
        dii -= row[j] * row[j];
      }
      row[i] = Math.sqrt(dii);
      Lp.push(row);
    }
    const yTri = new Array<number>(dParam).fill(0);
    for (let i = 0; i < dParam; i++) {
      let acc = rhs[i];
      for (let j = 0; j < i; j++) acc -= Lp[i][j] * yTri[j];
      yTri[i] = acc / Lp[i][i];
    }
    const mu = new Array<number>(dParam).fill(0);
    for (let i = dParam - 1; i >= 0; i--) {
      let acc = yTri[i];
      for (let j = i + 1; j < dParam; j++) acc -= Lp[j][i] * mu[j];
      mu[i] = acc / Lp[i][i];
    }
    // Sample θ = μ + Lp^{-T} z, z ∼ N(0, I)
    const z = new Array<number>(dParam).fill(0);
    for (let i = 0; i < dParam; i++) z[i] = draw();
    const offset = new Array<number>(dParam).fill(0);
    for (let i = dParam - 1; i >= 0; i--) {
      let acc = z[i];
      for (let j = i + 1; j < dParam; j++) acc -= Lp[j][i] * offset[j];
      offset[i] = acc / Lp[i][i];
    }
    const theta = new Array<number>(dParam).fill(0);
    for (let i = 0; i < dParam; i++) theta[i] = mu[i] + offset[i];
    return theta;
  };

  const prior = (): number[] => exactSampleAtBeta(0); // β=0 → just the prior
  const logPrior = (theta: number[]): number => {
    let bb = 0;
    for (let i = 0; i < theta.length; i++) bb += theta[i] * theta[i];
    return -0.5 * dParam * Math.log(2 * Math.PI * TAU2) - 0.5 * bb / TAU2;
  };
  const logLikelihood = (theta: number[]): number => {
    let sse = 0;
    for (let i = 0; i < N; i++) {
      let pred = 0;
      for (let j = 0; j < dParam; j++) pred += X[i][j] * theta[j];
      const r = Y_FIXED[i] - pred;
      sse += r * r;
    }
    return -0.5 * N * Math.log(2 * Math.PI * SIGMA2) - 0.5 * sse / SIGMA2;
  };

  const observed = aisEstimate(
    prior,
    logPrior,
    logLikelihood,
    100,
    (_theta, beta) => exactSampleAtBeta(beta),
    200,
  );
  record('AIS T=100 → closed-form log p(y)', logEvidence, observed, 0.30);
}

// -----------------------------------------------------------------------------
// 7. BIC asymptotic equivalence (sanity check, brief §3 Corollary 1)
// -----------------------------------------------------------------------------

header('7. BIC sanity (§3 Corollary 1)');

{
  // log p(y | θ̂) at d=4 equals the joint log-prob at MAP minus log p(θ̂)
  const d = 4;
  const X = polynomialDesignMatrix(X_GRID, d);
  const { mean } = polynomialPosteriorMoments(X, Y_FIXED, SIGMA2, TAU2);
  // log p(y | θ̂_MLE, M_d) — for a Gaussian-conjugate model with weakly
  // informative prior, the MAP and MLE roughly coincide; we use the MAP here.
  let sse = 0;
  for (let i = 0; i < N; i++) {
    let pred = 0;
    for (let j = 0; j < d + 1; j++) pred += X[i][j] * mean[j];
    const r = Y_FIXED[i] - pred;
    sse += r * r;
  }
  const logLikAtMAP = -0.5 * N * Math.log(2 * Math.PI * SIGMA2) - 0.5 * sse / SIGMA2;
  const negHalfBIC = bicApproximation(logLikAtMAP, d + 1, N);
  // -BIC/2 should be on the same order as log p(y|M_4); the gap is the O(1)
  // Bayesian content (a few nats). Range check: -50 < negHalfBIC < 50.
  const ok = Math.abs(negHalfBIC) < 50;
  rows.push({
    test: '-BIC/2 finite and on order of log p',
    expected: `|·| < 50`,
    observed: negHalfBIC.toFixed(4),
    ok,
  });
  if (ok) passed += 1;
  else failed += 1;
}

// -----------------------------------------------------------------------------
// Reporting
// -----------------------------------------------------------------------------

console.log(`\n${'─'.repeat(80)}`);
console.log(`${'Test'.padEnd(48)} ${'Expected'.padStart(12)} ${'Observed'.padStart(12)}  Status`);
console.log('─'.repeat(80));
for (const r of rows) {
  const status = r.ok ? '✓' : '✗';
  console.log(
    `${r.test.padEnd(48)} ${r.expected.padStart(12)} ${r.observed.padStart(12)}  ${status}`,
  );
}
console.log('─'.repeat(80));
console.log(`Passed: ${passed}   Failed: ${failed}`);

if (failed > 0) {
  process.exit(1);
}
process.exit(0);
